server:
  port: 9002

spring:
  application:
    name: customer-ui

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

feign:
  circuitbreaker:
    enabled: true

